name: Deploy Articles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl jq

      - name: Lade Artikel von Supabase
        env:
          SUPABASE_URL: https://ngtujvgsbymtxphwncuj.supabase.co
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          mkdir -p articles
          curl -s "$SUPABASE_URL/storage/v1/object/list/articles" \
            -H "Authorization: Bearer $SUPABASE_KEY" | jq -r '.[].name' > files.txt
          while read f; do
            curl -s "$SUPABASE_URL/storage/v1/object/articles/$f" \
              -H "Authorization: Bearer $SUPABASE_KEY" \
              -o "articles/$f"
          done < files.txt

      - name: Konvertiere Artikel zu HTML
        run: |
          mkdir -p public
          for file in articles/*; do
            name=$(basename "$file" .txt)
            echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>$name</title></head><body><article>" > public/$name.html
            cat "$file" >> public/$name.html
            echo "</article></body></html>" >> public/$name.html
          done

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/
          git commit -m "Neue Artikel gebaut" || echo "Nichts zu committen"
          git push
