name: Deploy Latest Article

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Download latest.json from Supabase
        env:
          SUPABASE_URL: https://ngtujvgsbymtxphwncuj.supabase.co
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          mkdir -p work
          echo "Herunterladen latest.json ..."
          # lade die Datei latest.json (private bucket) herunter
          curl -s -H "Authorization: Bearer $SUPABASE_KEY" \
            "$SUPABASE_URL/storage/v1/object/articles/latest.json" -o work/latest.json

          if [ ! -s work/latest.json ]; then
            echo "latest.json fehlt oder ist leer. Abbruch."
            exit 1
          fi

          echo "Inhalt:"
          cat work/latest.json | jq .

      - name: Build HTML from latest.json
        run: |
          mkdir -p public
          title=$(jq -r '.title // empty' work/latest.json)
          content=$(jq -r '.content // empty' work/latest.json)

          if [ -z "$title" ]; then
            echo "Kein title in latest.json gefunden. Abbruch."
            exit 1
          fi

          # Sanitize title -> safe filename
          # transliterate, lowercase, replace non-alnum with '-'
          title_slug=$(echo "$title" | iconv -t ascii//TRANSLIT 2>/dev/null || echo "$title")
          title_slug=$(echo "$title_slug" | tr '[:upper:]' '[:lower:]')
          title_slug=$(echo "$title_slug" | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-|-$//g')
          filename="public/${title_slug}.html"

          echo "Erstelle $filename (Titel: $title)"
          cat > "$filename" <<HTML
<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${title}</title>
  <style>
    body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial; max-width: 800px; margin: 2rem auto; line-height:1.6; padding: 0 1rem;}
    article { white-space: pre-line; } /* Newlines im content werden sichtbar */
  </style>
</head>
<body>
  <article>
$(jq -r '.content' work/latest.json)
  </article>
</body>
</html>
HTML

          echo "HTML gebaut: $filename"
          ls -l public || true

      - name: Commit & Push public/
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add public/
          git commit -m "Deploy latest article: ${GITHUB_RUN_ID}" || echo "Nothing to commit"
          git push
