name: Deploy Latest Article

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Download latest.json from Supabase
        env:
          SUPABASE_URL: https://ngtujvgsbymtxphwncuj.supabase.co
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          mkdir -p work
          echo "Herunterladen latest.json ..."
          curl -s -H "Authorization: Bearer $SUPABASE_KEY" \
            "$SUPABASE_URL/storage/v1/object/articles/latest.json" -o work/latest.json

          if [ ! -s work/latest.json ]; then
            echo "latest.json fehlt oder ist leer. Abbruch."
            exit 1
          fi

          echo "Inhalt:"
          cat work/latest.json | jq .

      - name: Build HTML from template
        run: |
          title=$(jq -r '.title // empty' work/latest.json)
          preview=$(jq -r '.preview // empty' work/latest.json)
          content=$(jq -r '.content // empty' work/latest.json)

          slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-|-$//g')
          filename="public/${slug}.html"

          # Template laden und Platzhalter ersetzen
          sed "s/{{TITLE}}/$title/g; s/{{PREVIEW}}/$preview/g; s/{{CONTENT}}/$content/g" template.html > "$filename"

          echo "HTML gebaut: $filename"

      - name: Commit & Push public/
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add public/
          git commit -m "Deploy latest article: ${GITHUB_RUN_ID}" || echo "Nothing to commit"
          git push
